<a href="https://colab.research.google.com/github/samhoon000/Job-Portal-Database-Analysis/blob/main/Linkedin_Job_Posting_Cleaning_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dataset link -->  https://www.kaggle.com/datasets/arshkon/linkedin-job-postings

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("C:\\Users\\lenovo\\OneDrive\\Desktop\\Job-Portal-Database-Analysis\\postings.csv", engine='python',on_bad_lines='skip')

In [2]:
df.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  object
 16  application_url             87184 non-null   object
 17  application_type            123849 non-null  object
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   object
 21  skills_desc                 2439 non-null    object
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   object
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  object
 26  currency                    36073 non-null   object
 27  compensation_type           36073 non-null   object
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), object(15)
memory usage: 29.3+ MB

In [4]:
df=df.drop(columns=['job_posting_url','application_url','zip_code','fips','expiry','closed_time'])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 25 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  application_type            123849 non-null  object
 16  formatted_experience_level  94440 non-null   object
 17  skills_desc                 2439 non-null    object
 18  listed_time                 123849 non-null  float64
 19  posting_domain              83881 non-null   object
 20  sponsored                   123849 non-null  int64
 21  work_type                   123849 non-null  object
 22  currency                    36073 non-null   object
 23  compensation_type           36073 non-null   object
 24  normalized_salary           36073 non-null   float64
dtypes: float64(10), int64(2), object(13)
memory usage: 23.6+ MB

In [6]:
cols_to_drop = [
    'med_salary',        # ~95% missing
    'skills_desc',       # almost empty
    'remote_allowed',    # too sparse + not critical
    'currency',          # tied to salary (but salary already weak)
    'compensation_type', # sparse
    'pay_period',        # sparse
    'posting_domain',    #not useful for analysis
    'normalized_salary'  #~70% missing → unreliable
]

In [7]:
df = df.drop(columns=cols_to_drop)

In [8]:
df['views'] = df['views'].fillna(0)
df['applies'] = df['applies'].fillna(0)
df['min_salary'] = df['min_salary'].fillna(0)
df['max_salary'] = df['max_salary'].fillna(0)

In [9]:
df=df.dropna(subset=['company_name','description'])
df['company_id']=df['company_id'].fillna(-1)
df['formatted_experience_level'] = df['formatted_experience_level'].fillna('Not Specified')

In [10]:
df['listed_time'] = pd.to_datetime(df['listed_time'], unit='ms')

In [11]:
df['original_listed_time'] = pd.to_datetime(df['original_listed_time'], unit='ms')

In [12]:
df.head()

,job_id,company_name,title,description,max_salary,location,company_id,views,min_salary,formatted_work_type,applies,original_listed_time,application_type,formatted_experience_level,listed_time,sponsored,work_type
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,"Princeton, NJ",2774458.0,20.0,17.0,Full-time,2.0,2024-04-17 23:45:08,ComplexOnsiteApply,Not Specified,2024-04-17 23:45:08,0,FULL_TIME
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,"Cincinnati, OH",64896719.0,8.0,45000.0,Full-time,0.0,2024-04-16 14:26:54,ComplexOnsiteApply,Not Specified,2024-04-16 14:26:54,0,FULL_TIME
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,"New Hyde Park, NY",766262.0,16.0,140000.0,Full-time,0.0,2024-04-12 04:23:32,ComplexOnsiteApply,Not Specified,2024-04-12 04:23:32,0,FULL_TIME
5,91700727,Downtown Raleigh Alliance,Economic Development and Planning Intern,Job summary:The Economic Development & Plannin...,20.0,"Raleigh, NC",1481176.0,9.0,14.0,Internship,4.0,2024-04-18 16:01:39,ComplexOnsiteApply,Not Specified,2024-04-18 16:01:39,0,INTERNSHIP
6,103254301,Raw Cereal,Producer,Company DescriptionRaw Cereal is a creative de...,300000.0,United States,81942316.0,7.0,60000.0,Contract,1.0,2024-04-11 18:43:39,SimpleOnsiteApply,Not Specified,2024-04-11 18:43:39,0,CONTRACT

In [13]:
# df.to_csv("Job_Postings.csv")

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122124 entries, 0 to 123848
Data columns (total 17 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      122124 non-null  int64
 1   company_name                122124 non-null  object
 2   title                       122124 non-null  object
 3   description                 122124 non-null  object
 4   max_salary                  122124 non-null  float64
 5   location                    122124 non-null  object
 6   company_id                  122124 non-null  float64
 7   views                       122124 non-null  float64
 8   min_salary                  122124 non-null  float64
 9   formatted_work_type         122124 non-null  object
 10  applies                     122124 non-null  float64
 11  original_listed_time        122124 non-null  datetime64[ns]
 12  application_type            122124 non-null  object
 13  formatted_experience_level  122124 non-null  object
 14  listed_time                 122124 non-null  datetime64[ns]
 15  sponsored                   122124 non-null  int64
 16  work_type                   122124 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(2), object(8)
memory usage: 16.8+ MB

In [15]:
# Sample data for faster analysis (optional, can be removed if full dataset is manageable)
df = df.sample(10000, random_state=42)

In [16]:
companies=df[['company_id','company_name']]

In [17]:
companies.head()

        company_id                          company_name
48078     418039.0                            Herspiegel
101389     93254.0                     MyMichigan Health
118909  71131832.0             Ochsner Lafayette General
5440      474443.0  U.S. Tsubaki Power Transmission, LLC
98739      27549.0              National Bank of Arizona

In [18]:
jobs=df[[
    'job_id',
    'title',
    'company_id',
    'location',
    'formatted_experience_level',
    'work_type',
    'formatted_work_type',
    'application_type',
    'sponsored'
    ]].rename(columns={'formatted_experience_level':'experience_level'})

In [19]:
jobs.head()

,job_id,title,company_id,location,experience_level,work_type,formatted_work_type,application_type,sponsored
48078,3901335560,Sustainability Specialist (Intern or Coop),418039.0,Raleigh-Durham-Chapel Hill Area,Entry level,INTERNSHIP,Internship,OffsiteApply,0
101389,3905247916,Imaging Services Technologist,93254.0,"Midland, MI",Not Specified,FULL_TIME,Full-time,OffsiteApply,0
118909,3906220675,Radiologic Technologist - OLGMC - Radiology - PRN,71131832.0,"Lafayette, LA",Mid-Senior level,FULL_TIME,Full-time,OffsiteApply,0
5440,3885100607,Electrical/Mechanical Repair Specialist - 24/7...,474443.0,"Chicopee, MA",Not Specified,FULL_TIME,Full-time,OffsiteApply,0
98739,3904987490,Branch Manager - Deer Valley (AZ),27549.0,"Phoenix, AZ",Mid-Senior level,FULL_TIME,Full-time,OffsiteApply,0

In [20]:
job_metrics=df[['job_id','views','applies']]

In [21]:
job_metrics.head()

            job_id  views  applies
48078   3901335560   69.0      1.0
101389  3905247916    1.0      0.0
118909  3906220675    4.0      0.0
5440    3885100607    2.0      0.0
98739   3904987490    6.0      0.0

In [22]:
salaries=df[['job_id','min_salary','max_salary']]

In [23]:
salaries.head()

            job_id  min_salary  max_salary
48078   3901335560         0.0         0.0
101389  3905247916         0.0         0.0
118909  3906220675         0.0         0.0
5440    3885100607         0.0         0.0
98739   3904987490         0.0         0.0

In [24]:
job_time=df[['job_id','listed_time','original_listed_time']]

In [25]:
job_time.head()

            job_id         listed_time original_listed_time
48078   3901335560 2024-04-18 15:12:08  2024-04-18 11:57:31
101389  3905247916 2024-04-18 19:31:55  2024-04-18 19:20:24
118909  3906220675 2024-04-19 21:14:37  2024-04-19 20:59:33
5440    3885100607 2024-04-06 07:39:09  2024-04-06 07:39:09
98739   3904987490 2024-04-18 16:31:15  2024-04-17 00:00:00

In [26]:
companies.to_csv('companies.csv',index=False,header=False)
jobs.to_csv('jobs.csv',index=False,header=False)
job_metrics.to_csv('job_metrics.csv',index=False,header=False)
salaries.to_csv('salaries.csv',index=False,header=False)
job_time.to_csv('job_time.csv',index=False,header=False)

In [27]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 48078 to 68513
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   company_id    10000 non-null  float64
 1   company_name  10000 non-null  object
dtypes: float64(1), object(1)
memory usage: 234.4+ KB

In [28]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 48078 to 68513
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               10000 non-null  int64
 1   title                10000 non-null  object
 2   company_id           10000 non-null  float64
 3   location             10000 non-null  object
 4   experience_level     10000 non-null  object
 5   work_type            10000 non-null  object
 6   formatted_work_type  10000 non-null  object
 7   application_type     10000 non-null  object
 8   sponsored            10000 non-null  int64
dtypes: float64(1), int64(2), object(6)
memory usage: 781.2+ KB

In [29]:
job_metrics.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 48078 to 68513
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   job_id   10000 non-null  int64
 1   views    10000 non-null  float64
 2   applies  10000 non-null  float64
dtypes: float64(2), int64(1)
memory usage: 312.5 KB

In [30]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 48078 to 68513
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   job_id      10000 non-null  int64
 1   min_salary  10000 non-null  float64
 2   max_salary  10000 non-null  float64
dtypes: float64(2), int64(1)
memory usage: 312.5 KB

In [31]:
job_time.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 48078 to 68513
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   job_id                10000 non-null  int64
 1   listed_time           10000 non-null  datetime64[ns]
 2   original_listed_time  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1)
memory usage: 312.5 KB